spring.application.name=dolibarr-backend

dolibarr.base-url=http://localhost/dolibarr/htdocs/api/index.php
dolibarr.api-key=P3wdXDOq5s2fX72Te8Iv8AoE711dBjLe
dolibarr.protected-user-ids=3
dolibarr.protected-user-logins=alan

backoffice.code-unique=0000
